apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqrx-app
  namespace: platform
spec:
  selector:
    matchLabels:
      run: sqrx-app
  replicas: 1
  template:
    metadata:
      labels:
        run: sqrx-app
    spec:
      containers:
        - name: sqrx-app
          image: manigandanjeff/sqrx-app:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 2500Mi
              cpu: 500m
            requests:
              memory: 2000Mi
              cpu: 250m
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: latest
