apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbix-rbi
  namespace: platform
spec:
  selector:
    matchLabels:
      run: rbix-rbi
  replicas: 1
  template:
    metadata:
      labels:
        run: rbix-rbi
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: rbix-config
            items:
              - key: config.rbi.json
                path: config.rbi.json
      containers:
        - name: rbix-rbi
          image: manigandanjeff/rbix-rbi:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 2500Mi
              cpu: 700m
            requests:
              memory: 2000Mi
              cpu: 500m
          volumeMounts:
            - name: config-volume
              mountPath: /config
          imagePullPolicy: Always
          env:
            - name: ENV
              value: dev-k8s
            - name: PORT
