apiVersion: v1
kind: Service
metadata:
  name: rbix-angago
  namespace: platform
  labels:
    run: rbix-angago
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: rbix-angago