apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbix-api
  namespace: platform
spec:
  selector:
    matchLabels:
      run: rbix-api
  replicas: 1
  template:
    metadata:
      labels:
        run: rbix-api
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: rbix-config
            items:
              - key: config.api.json
                path: config.api.json
      containers:
        - name: rbix-api
          image: manigandanjeff/rbix-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 100Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 500m
          volumeMounts:
            - name: config-volume
              mountPath: /config
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: latest
