apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbix-app
  namespace: platform
spec:
  selector:
    matchLabels:
      run: rbix-app
  replicas: 1
  template:
    metadata:
      labels:
        run: rbix-app
    spec:
      containers:
        - name: rbix-app
          image: manigandanjeff/rbix-app:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 2500Mi
              cpu: 500m
            requests:
              memory: 2000Mi
              cpu: 250m
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: latest
