apiVersion: v1
kind: Service
metadata:
  name: rbix-app
  namespace: platform
  labels:
    run: rbix-app
spec:
  type: NodePort
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    run: rbix-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbix-app-gateway
  namespace: platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: rbix-app-gateway
spec:
  rules:
  - host: app.rbixlabs.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rbix-app
            port:
              number: 3000
