apiVersion: v1
kind: ConfigMap
metadata:
    name: rbix-config
    namespace: platform
data:
    config.api.json: |
        {
          "ENV": "dev-k8s",
          "PORT": "8080",
          "RBIX_WS_LOADBALANCER_HOST" : "in.malwaresamathi.rbixlabs.com",
          "RBIX_RBI_IMAGE": "manigandanjeff/rbix-rbi:latest"
        }
    config.angago.json: |
        {
          "ENV": "dev-k8s",
          "PORT": "8081",
          "RBIX_RBI_BOX_PORT" : "8888",
          "RBIX_API_SERVER_HOST": "http://api.rbixlabs.com"
        }
    config.rbi.json: |
        {
          "ENV": "dev-k8s",
          "PORT": "8888"
        }
