apiVersion: v1
kind: Service
metadata:
  name: sqrx-angago
  namespace: platform
  labels:
    run: sqrx-angago
spec:
  type: NodePort
  ports:
  - name: web
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    run: sqrx-angago
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sqrx-angago-gateway
  namespace: platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: sqrx-angago-gateway
spec:
  rules:
  - host: in.malwareriplabs.sqrx.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sqrx-angago
            port:
              number: 8081
